// Generated by CoffeeScript 1.6.3
(function() {
  var find_col, grid_size;

  $(function() {
    var fragment;
    fragment = document.createDocumentFragment();
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].forEach(function() {
      var row;
      row = document.createElement('div');
      row.className = 'row';
      [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].forEach(function() {
        var div;
        div = document.createElement('div');
        div.className = 'cell';
        return row.appendChild(div);
      });
      return fragment.appendChild(row);
    });
    document.getElementById('grids').appendChild(fragment);
    return $('#grids').on({
      click: function() {
        $(this).toggleClass('clicked');
        return $('#coords').val(find_col(this));
      }
    }, '.cell');
  });

  find_col = function(cell) {
    var child, i, map, row, x, y, _i, _j, _len, _len1, _ref, _ref1;
    row = $(cell).parent('.row');
    map = row.parent('#grids');
    _ref = row.children();
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      child = _ref[i];
      if (child === cell) {
        x = i;
        break;
      }
    }
    _ref1 = map.children('');
    for (i = _j = 0, _len1 = _ref1.length; _j < _len1; i = ++_j) {
      child = _ref1[i];
      if (child === row[0]) {
        y = i;
        break;
      }
    }
    return [y, x];
  };

  grid_size = function() {
    return 10;
  };

}).call(this);
