// Generated by CoffeeScript 1.6.3
(function() {
  var grid_size;

  $(function() {
    var fragment;
    fragment = document.createDocumentFragment();
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].forEach(function() {
      var row;
      row = document.createElement('div');
      row.className = 'row';
      [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].forEach(function() {
        var div;
        div = document.createElement('div');
        div.className = 'cell';
        return row.appendChild(div);
      });
      return fragment.appendChild(row);
    });
    document.getElementById('grids').appendChild(fragment);
    return $('#grids').on({
      click: function() {
        return $(this).toggleClass('clicked');
      }
    }, '.cell');
  });

  grid_size = function() {
    return 10;
  };

}).call(this);
